name: Deploy
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: taiki-e/install-action@just
      - name: cargo check
        run: just check

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: taiki-e/install-action@just
      - name: cargo fmt
        run: just fmt-check

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: clippy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: taiki-e/install-action@just
      - name: cargo clippy
        run: just clippy-lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - check
      - clippy
      - fmt
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@just
      - name: cargo test
        run: just test

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs:
      - test
    concurrency:
      group: deploy-group
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: emilpriver/geni@main
        with:
          database_url: ${{ secrets.DATABASE_URL }}
          database_token: ${{ secrets.DATABASE_TOKEN }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WHPROXY_TOKEN }}
