[package]
name = "import"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
chrono-tz = "0.10.1"
csv = "1.3.1"
dotenvy = "0.15.7"
indicatif = "0.17.11"
libsql = "0.6.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tables = { path = "../../crates/tables" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
